selary:
  train_dataset: C:\Users\snw12\Desktop\Scince_shit\AI\MyProject\datasets\train.csv
  test_dataset: C:\Users\snw12\Desktop\Scince_shit\AI\MyProject\datasets\test.csv
  train_refactor: C:\Users\snw12\Desktop\Scince_shit\AI\MyProject\datasets\train_2.csv
  test_refactor: C:\Users\snw12\Desktop\Scince_shit\AI\MyProject\datasets\test_2.csv
