selary:
  train_dataset: C:\Users\snw12\Desktop\Scince_shit\AI\PredictCreditScoreinit\datasets\train.csv
  test_dataset: C:\Users\snw12\Desktop\Scince_shit\AI\PredictCreditScoreinit\datasets\test.csv
  train_refactor: C:\Users\snw12\Desktop\Scince_shit\AI\PredictCreditScoreinit\datasets\train_3.csv
  test_refactor: C:\Users\snw12\Desktop\Scince_shit\AI\PredictCreditScoreinit\datasets\test_3.csv
