selary:
  train_dataset: D:\study\AI\PredictCreditScoreinit\datasets\train.csv
  test_dataset: D:\study\AI\PredictCreditScoreinit\datasets\test.csv
  train_refactor: D:\study\AI\PredictCreditScoreinit\datasets\train_3.csv
  test_refactor: D:\study\AI\PredictCreditScoreinit\datasets\test_3.csv
